# Generated by Django 5.2.7 on 2025-12-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('caminho_foto', models.CharField(max_length=255)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
