# Generated by Django 4.1.13 on 2025-12-11 20:33

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('caminho_foto', models.CharField(max_length=255)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('ultimo_reconhecimento', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
