# Generated by Django 5.2.7 on 2025-12-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ultimo_reconhecimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
