export let containerid = $('#container')
export let retorno = $('#profile')
export let barra = $('#barraponto')
export let icone = $('#icone-error')
export let usuario = $('#username')
export let senha = $('#password')